# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDOss0YUDfgvZbu7jq4lfp7v1BX7yWK_
"""

import math
from collections import Counter

# Small training dataset
# Features: [Height, Weight]
X_train = [
    [150, 50],
    [160, 55],
    [170, 65],
    [175, 70],
    [180, 80],
    [155, 52]
]

# Class labels
y_train = [
    "Class A",
    "Class A",
    "Class B",
    "Class B",
    "Class B",
    "Class A"
]

# Test dataset
X_test = [
    [165, 60],
    [178, 75],
    [152, 51]
]

y_test = [
    "Class A",
    "Class B",
    "Class A"
]

# Euclidean distance function
def euclidean_distance(p1, p2):
    return math.sqrt(sum((a - b) ** 2 for a, b in zip(p1, p2)))

# KNN prediction function
def knn_predict(X_train, y_train, test_point, k):
    distances = []

    for i in range(len(X_train)):
        distance = euclidean_distance(X_train[i], test_point)
        distances.append((distance, y_train[i]))

    # Sort according to distance
    distances.sort(key=lambda x: x[0])

    # Select K nearest neighbours
    nearest_neighbors = distances[:k]

    # Get their class labels
    labels = [label for distance, label in nearest_neighbors]

    # Majority voting
    prediction = Counter(labels).most_common(1)[0][0]

    return prediction

# Get K from user
k = int(input("Enter the value of K: "))

if k <= 0 or k > len(X_train):
    print("Invalid value of K!")
else:
    predictions = []

    print("\nPredictions:")

    for i, test_point in enumerate(X_test):
        prediction = knn_predict(X_train, y_train, test_point, k)
        predictions.append(prediction)

        print("Test Instance:", test_point)
        print("Predicted Class:", prediction)
        print("Actual Class:", y_test[i])
        print()

    # Calculate accuracy
    correct = sum(predictions[i] == y_test[i] for i in range(len(y_test)))
    accuracy = (correct / len(y_test)) * 100

    print("Predictions:", predictions)
    print("Accuracy: {:.2f}%".format(accuracy))



import numpy as np

# --------------------------------
# Different Dataset
# Features:
# [Study Hours, Attendance (%)]
# --------------------------------

X = np.array([
    [1, 50],
    [2, 55],
    [2, 60],
    [3, 62],
    [4, 65],
    [5, 70],
    [6, 75],
    [7, 80],
    [8, 85],
    [9, 90]
], dtype=float)

# 0 = Fail, 1 = Pass
y = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])


# --------------------------------
# Sigmoid Function
# --------------------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


# --------------------------------
# Train Logistic Regression
# --------------------------------
def train_model(X, y, learning_rate, epochs):

    weights = np.zeros(X.shape[1])
    bias = 0

    for epoch in range(epochs):

        # Linear model
        z = np.dot(X, weights) + bias

        # Sigmoid output
        y_pred = sigmoid(z)

        # Gradients
        dw = np.dot(X.T, (y_pred - y)) / len(y)
        db = np.sum(y_pred - y) / len(y)

        # Update weights
        weights = weights - learning_rate * dw
        bias = bias - learning_rate * db

    return weights, bias


# --------------------------------
# Prediction Function
# --------------------------------
def predict(X, weights, bias):

    z = np.dot(X, weights) + bias

    probability = sigmoid(z)

    prediction = (probability >= 0.5).astype(int)

    return probability, prediction


# --------------------------------
# User Input
# --------------------------------
learning_rate = float(input("Enter learning rate: "))
epochs = int(input("Enter number of epochs: "))


# Train model
weights, bias = train_model(
    X, y, learning_rate, epochs
)


# --------------------------------
# Test Dataset
# --------------------------------
X_test = np.array([
    [2, 58],
    [5, 68],
    [7, 78],
    [9, 88]
], dtype=float)

# Actual classes
y_test = np.array([0, 1, 1, 1])


# --------------------------------
# Prediction
# --------------------------------
probability, prediction = predict(
    X_test, weights, bias
)


# --------------------------------
# Display Results
# --------------------------------
print("\n--- Classification Results ---")

for i in range(len(X_test)):

    print(
        "Study Hours:", X_test[i][0],
        "Attendance:", X_test[i][1],
        "Sigmoid Output:", round(probability[i], 4),
        "Predicted Class:", prediction[i],
        "Actual Class:", y_test[i]
    )


# --------------------------------
# Accuracy
# --------------------------------
accuracy = np.mean(prediction == y_test) * 100

print("\nWeights:", weights)
print("Bias:", bias)
print("Accuracy: {:.2f}%".format(accuracy))