# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eb3APph-hfqurc-t-45pPesPzySzVIeG
"""

# Linear Regression Example

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# Sample dataset
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # Independent variable
y = np.array([2, 4, 5, 4, 5])                 # Dependent variable

# Create Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Predict values
y_pred = model.predict(X)

# Display coefficients
print("Slope (m):", model.coef_[0])
print("Intercept (b):", model.intercept_)

# Predict for a new value
x_new = np.array([[6]])
prediction = model.predict(x_new)
print("Prediction for x = 6:", prediction[0])

# Plot data points and regression line
plt.scatter(X, y, label="Actual Data")
plt.plot(X, y_pred, label="Regression Line")
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Linear Regression")
plt.legend()
plt.show()