# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eb3APph-hfqurc-t-45pPesPzySzVIeG
"""

# Linear Regression using House Price Dataset

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Sample Dataset
data = {
    'House_Size': [800, 1000, 1200, 1500, 1800, 2000, 2200, 2500],
    'House_Price': [150000, 180000, 210000, 250000, 280000, 310000, 340000, 390000]
}

# Create DataFrame
df = pd.DataFrame(data)

# Features (X) and Target (y)
X = df[['House_Size']]
y = df['House_Price']

# Create Linear Regression Model
model = LinearRegression()

# Train the Model
model.fit(X, y)

# Predict Prices
predictions = model.predict(X)

# Display Results
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Predict price for a new house
new_house = [[1700]]
predicted_price = model.predict(new_house)

print("Predicted Price for 1700 sq.ft house: $", round(predicted_price[0], 2))

# Plot
plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X, predictions, color='red', label='Regression Line')
plt.xlabel("House Size (sq.ft)")
plt.ylabel("House Price ($)")
plt.title("Linear Regression - House Price Prediction")
plt.legend()
plt.grid(True)
plt.show()

# Linear Regression Example

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# Sample dataset
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # Independent variable
y = np.array([2, 4, 5, 4, 5])                 # Dependent variable

# Create Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Predict values
y_pred = model.predict(X)

# Display coefficients
print("Slope (m):", model.coef_[0])
print("Intercept (b):", model.intercept_)

# Predict for a new value
x_new = np.array([[6]])
prediction = model.predict(x_new)
print("Prediction for x = 6:", prediction[0])

# Plot data points and regression line
plt.scatter(X, y, label="Actual Data")
plt.plot(X, y_pred, label="Regression Line")
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Linear Regression")
plt.legend()
plt.show()